import { useEffect, useState, type ComponentType, type ReactNode } from 'react';
import { ArrowLeft, Building2, Calculator, Moon, Package, Plus, Scale, Sun, Target, Trash2, TrendingUp } from 'lucide-react';
import { AnimatePresence, motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { useTheme } from '../theme/ThemeContext';

type Tool = 'setup' | 'margin' | 'goal' | 'break-even' | 'valuation';
type FixedCost = { id: string; label: string; value: number };
type Product = { id: string; name: string; price: number; productCost: number; fees: number; monthlyUnits: number };
type BusinessData = { profitGoal: number; workDays: number; fixedCosts: FixedCost[]; products: Product[]; annualRevenue: number; annualProfit: number; annualGrowth: number; ownerDependence: number };
const newProduct = (name = 'Produto principal'): Product => ({ id: crypto.randomUUID(), name, price: 0, productCost: 0, fees: 0, monthlyUnits: 0 });
const initialData: BusinessData = { profitGoal: 0, workDays: 22, fixedCosts: [{ id: 'rent', label: 'Aluguel / espaço', value: 0 }, { id: 'payroll', label: 'Salários e pró-labore', value: 0 }, { id: 'marketing', label: 'Marketing', value: 0 }, { id: 'systems', label: 'Sistemas e assinaturas', value: 0 }], products: [newProduct()], annualRevenue: 0, annualProfit: 0, annualGrowth: 0, ownerDependence: 50 };
type IconType = ComponentType<{ size?: number; strokeWidth?: number }>;
const tools: Array<{ id: Tool; name: string; short: string; icon: IconType }> = [
  { id: 'margin', name: 'Margem & preço', short: 'Descubra quanto sobra em cada venda.', icon: Calculator },
  { id: 'goal', name: 'Meta de lucro', short: 'Saiba quanto precisa vender para chegar lá.', icon: Target },
  { id: 'break-even', name: 'Ponto de equilíbrio', short: 'Encontre o mínimo para não ter prejuízo.', icon: Scale },
  { id: 'valuation', name: 'Valuation da empresa', short: 'Estime uma faixa de valor para o negócio.', icon: TrendingUp },
];
const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
const number = new Intl.NumberFormat('pt-BR', { maximumFractionDigits: 1 });
const safe = (value: number) => Number.isFinite(value) && value > 0 ? value : 0;
const contribution = (product: Product) => product.price - product.productCost - product.price * product.fees / 100;

export function IntelligenceCenter() {
  const [active, setActive] = useState<Tool>('setup');
  const [data, setData] = useState<BusinessData>(() => { try { const saved = JSON.parse(localStorage.getItem('meta_business_data') || 'null'); if (!saved) return initialData; return { ...initialData, ...saved, products: saved.products?.length ? saved.products : [{ ...newProduct(), price: saved.price || 0, productCost: saved.productCost || 0, fees: saved.fees || 0 }] }; } catch { return initialData; } });
  const [productId, setProductId] = useState(() => data.products[0]?.id || '');
  const navigate = useNavigate();
  useEffect(() => { localStorage.setItem('meta_business_data', JSON.stringify(data)); }, [data]);
  const update = <K extends keyof BusinessData>(key: K, value: BusinessData[K]) => setData(current => ({ ...current, [key]: value }));
  const selectedProduct = data.products.find(product => product.id === productId) || data.products[0];
  const filled = [data.profitGoal, ...data.fixedCosts.map(cost => cost.value), ...data.products.flatMap(product => [product.price, product.productCost])].filter(value => value > 0).length;
  const total = 1 + data.fixedCosts.length + data.products.length * 2;
  return <div className="min-h-screen px-6 py-8 md:px-10 md:py-10 lg:px-14 lg:py-12 text-[#171716] dark:text-white"><div className="max-w-[1440px] mx-auto">
    <header className="flex flex-col md:flex-row md:items-end justify-between gap-8 mb-10"><div>
      <button onClick={() => navigate('/home')} className="flex items-center gap-2 text-black/45 dark:text-white/45 hover:text-black dark:hover:text-white text-sm mb-7 transition-colors"><ArrowLeft size={15} /> Voltar para início</button>
      <div className="flex items-center gap-4 mb-4"><span className="w-12 h-px bg-[#a68f63]" /><span className="meta-label !mb-0">Decisão com clareza</span></div>
      <h1 className="text-5xl md:text-7xl font-light tracking-tight" style={{ fontFamily: 'var(--font-serif)' }}>Ferramentas<br /><span className="text-black/30 dark:text-white/30 italic">de negócio.</span></h1>
    </div><div className="flex flex-col items-start md:items-end gap-5"><AppearanceSwitch /><p className="max-w-sm text-black/50 dark:text-white/50 leading-relaxed md:text-right">Simulações rápidas para transformar custos, metas e preços em decisões objetivas. Os cálculos são estimativas gerenciais.</p></div></header>
    <div className="grid md:grid-cols-[250px_minmax(0,1fr)] xl:grid-cols-[290px_minmax(0,1fr)] gap-6 lg:gap-8 items-start"><nav aria-label="Ferramentas financeiras" className="space-y-3 md:sticky md:top-8"><button onClick={() => setActive('setup')} className={`w-full text-left rounded-2xl border p-5 transition-all ${active === 'setup' ? 'bg-[#a68f63]/10 border-[#a68f63]/30 shadow-[inset_2px_0_0_#a68f63]' : 'border-black/[0.07] dark:border-white/[0.08] bg-white/30 dark:bg-white/[0.03]'}`}><div className="flex gap-4"><span className="w-10 h-10 rounded-full border border-[#a68f63]/35 text-[#8d7852] dark:text-[#c7b182] flex items-center justify-center shrink-0"><Building2 size={17} strokeWidth={1.4} /></span><div><span className="text-[9px] tracking-[.2em] text-[#a68f63]">COMECE AQUI</span><h2 className="font-medium mt-1">Dados do negócio</h2><p className="text-xs text-black/40 dark:text-white/40 mt-1">{filled} de {total} dados preenchidos</p></div></div><div className="h-1 bg-black/[0.06] dark:bg-white/[0.08] rounded-full mt-4 overflow-hidden"><span className="block h-full bg-[#a68f63] transition-all" style={{ width: `${Math.min(100, filled / total * 100)}%` }} /></div></button><div className="pt-3 pb-1 px-2 meta-label">Seus resultados</div>{tools.map((tool, index) => <ToolButton key={tool.id} tool={tool} index={index + 1} active={active === tool.id} onClick={() => setActive(tool.id)} />)}</nav>
      <section className="min-h-[580px] rounded-[2rem] bg-white/65 dark:!bg-[#151515] border border-black/[0.08] dark:border-white/[0.1] backdrop-blur-3xl shadow-[0_35px_100px_rgba(57,49,34,.08),inset_0_1px_0_white] dark:shadow-[0_35px_100px_rgba(0,0,0,.3)] overflow-hidden"><AnimatePresence mode="wait"><motion.div key={active} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: .35 }}>{active === 'setup' ? <BusinessSetup data={data} update={update} onReady={() => setActive('margin')} /> : active === 'valuation' ? <ValuationTool data={data} update={update} /> : <><ProductPicker products={data.products} selected={selectedProduct.id} onChange={setProductId} />{active === 'margin' ? <MarginTool data={data} product={selectedProduct} /> : active === 'goal' ? <GoalTool data={data} product={selectedProduct} /> : <BreakEvenTool data={data} product={selectedProduct} />}</>}</motion.div></AnimatePresence></section>
    </div>
  </div></div>;
}

function AppearanceSwitch() {
  const { theme, toggleTheme } = useTheme();
  return <div className="inline-flex items-center gap-1 rounded-full border border-black/10 dark:border-white/10 bg-white/55 dark:bg-white/[0.06] p-1.5 backdrop-blur-xl" aria-label="Aparência">
    <button type="button" onClick={theme === 'dark' ? toggleTheme : undefined} className={`flex items-center gap-2 rounded-full px-3 py-2 text-[10px] uppercase tracking-[.14em] transition-all ${theme === 'light' ? 'bg-white text-black shadow-sm' : 'text-white/35 hover:text-white/70'}`}><Sun size={14} strokeWidth={1.5} /> Claro</button>
    <button type="button" onClick={theme === 'light' ? toggleTheme : undefined} className={`flex items-center gap-2 rounded-full px-3 py-2 text-[10px] uppercase tracking-[.14em] transition-all ${theme === 'dark' ? 'bg-white/12 text-white shadow-sm' : 'text-black/35 hover:text-black/70'}`}><Moon size={14} strokeWidth={1.5} /> Noturno</button>
  </div>;
}

function ToolButton({ tool, index, active, onClick }: { tool: typeof tools[number]; index: number; active: boolean; onClick: () => void }) {
  const Icon = tool.icon;
  return <button onClick={onClick} className={`w-full text-left rounded-2xl border p-5 transition-all ${active ? 'bg-white/75 dark:bg-white/10 border-black/10 dark:border-white/15 shadow-[inset_2px_0_0_#a68f63,0_15px_45px_rgba(44,39,29,.06)]' : 'border-transparent hover:border-black/[0.07] dark:hover:border-white/[0.08] hover:bg-white/35 dark:hover:bg-white/[0.04]'}`}><div className="flex items-start gap-4"><span className={`w-10 h-10 rounded-full border flex items-center justify-center shrink-0 ${active ? 'border-[#a68f63]/40 text-[#8d7852] dark:text-[#c7b182]' : 'border-black/10 dark:border-white/10 text-black/30 dark:text-white/30'}`}><Icon size={17} strokeWidth={1.4} /></span><div><span className="text-[9px] tracking-[.22em] text-[#a68f63]">0{index}</span><h2 className="font-medium mt-1">{tool.name}</h2><p className="text-xs text-black/40 dark:text-white/40 mt-1.5 leading-relaxed">{tool.short}</p></div></div></button>;
}

function ToolShell({ eyebrow, title, description, children, results }: { eyebrow: string; title: string; description: string; children: ReactNode; results: ReactNode }) {
  return <div className="grid lg:grid-cols-[minmax(0,1fr)_minmax(280px,.82fr)] min-h-[580px]"><div className="p-7 md:p-8 xl:p-11 border-b lg:border-b-0 lg:border-r border-black/[0.07] dark:border-white/[0.08]"><p className="meta-label">{eyebrow}</p><h2 className="text-3xl xl:text-4xl font-light mb-4" style={{ fontFamily: 'var(--font-serif)' }}>{title}</h2><p className="text-sm text-black/45 dark:text-white/45 leading-relaxed max-w-xl mb-9">{description}</p><div className="grid xl:grid-cols-2 gap-5">{children}</div></div><div className="p-7 md:p-8 xl:p-11 bg-white/25 dark:!bg-black/10 flex flex-col"><p className="meta-label">Resultado instantâneo</p>{results}</div></div>;
}

function Field({ label, value, onChange, suffix = 'R$' }: { label: string; value: number; onChange: (value: number) => void; suffix?: string }) {
  return <label className="block"><span className="text-xs text-black/50 dark:text-white/50 block mb-2">{label}</span><span className="relative block"><input type="number" min="0" step="0.01" value={value || ''} onChange={event => onChange(Number(event.target.value))} className="w-full rounded-xl bg-white/70 dark:bg-white/[0.06] border border-black/10 dark:border-white/10 py-4 pl-4 pr-12 text-lg text-black dark:text-white outline-none focus:border-[#a68f63] transition-colors" /><span className="absolute right-4 top-1/2 -translate-y-1/2 text-xs text-black/30 dark:text-white/30">{suffix}</span></span></label>;
}
function Metric({ label, value, hero = false }: { label: string; value: string; hero?: boolean }) { return <div className={`border-b border-black/[0.08] dark:border-white/[0.08] py-5 ${hero ? 'mb-2' : ''}`}><p className="text-[10px] uppercase tracking-[.18em] text-black/35 dark:text-white/35 mb-2">{label}</p><p className={`${hero ? 'text-4xl md:text-5xl' : 'text-2xl'} font-light`} style={{ fontFamily: 'var(--font-serif)' }}>{value}</p></div>; }
function Advice({ children }: { children: ReactNode }) { return <div className="mt-auto pt-8"><div className="rounded-2xl border border-[#a68f63]/25 bg-[#a68f63]/[0.08] p-5"><p className="text-[10px] uppercase tracking-[.2em] text-[#8d7852] dark:text-[#c7b182] mb-2">Leitura estratégica</p><p className="text-sm text-black/60 dark:text-white/60 leading-relaxed">{children}</p></div><p className="text-[10px] text-black/30 dark:text-white/30 mt-4 leading-relaxed">Use como referência gerencial. Impostos, taxas e regras contábeis podem variar.</p></div>; }

function BusinessSetup({ data, update, onReady }: { data: BusinessData; update: <K extends keyof BusinessData>(key: K, value: BusinessData[K]) => void; onReady: () => void }) {
  const totalFixed = data.fixedCosts.reduce((sum, cost) => sum + cost.value, 0);
  const updateCost = (id: string, patch: Partial<FixedCost>) => update('fixedCosts', data.fixedCosts.map(cost => cost.id === id ? { ...cost, ...patch } : cost));
  const addCost = () => update('fixedCosts', [...data.fixedCosts, { id: crypto.randomUUID(), label: 'Outro custo fixo', value: 0 }]);
  const removeCost = (id: string) => update('fixedCosts', data.fixedCosts.filter(cost => cost.id !== id));
  const updateProduct = (id: string, patch: Partial<Product>) => update('products', data.products.map(product => product.id === id ? { ...product, ...patch } : product));
  const addProduct = () => update('products', [...data.products, newProduct(`Produto ${data.products.length + 1}`)]);
  const removeProduct = (id: string) => data.products.length > 1 && update('products', data.products.filter(product => product.id !== id));
  return <div className="p-7 md:p-10 xl:p-12">
    <div className="max-w-3xl"><p className="meta-label">Passo 01 — sua base</p><h2 className="text-4xl md:text-5xl font-light mb-4" style={{ fontFamily: 'var(--font-serif)' }}>Conte como o negócio funciona.</h2><p className="text-black/50 dark:text-white/50 leading-relaxed mb-10">Preencha uma vez. Esses números alimentam automaticamente as três ferramentas e ficam salvos neste dispositivo para as próximas consultas.</p></div>
    <div className="grid xl:grid-cols-2 gap-6">
      <SetupGroup number="01" title="Seus produtos" help="Cadastre quantos produtos quiser. Cada um terá sua própria simulação."><div className="space-y-4">{data.products.map((product,index)=><div key={product.id} className="rounded-xl border border-black/[0.08] dark:border-white/[0.08] p-4"><div className="flex items-center gap-3 mb-4"><Package size={16} className="text-[#a68f63]"/><input aria-label={`Nome do produto ${index+1}`} value={product.name} onChange={event=>updateProduct(product.id,{name:event.target.value})} className="bg-transparent border-b border-black/10 dark:border-white/10 py-2 flex-1 outline-none focus:border-[#a68f63]"/><button disabled={data.products.length===1} aria-label={`Excluir ${product.name}`} onClick={()=>removeProduct(product.id)} className="text-black/25 disabled:opacity-20 hover:text-red-500"><Trash2 size={15}/></button></div><div className="grid sm:grid-cols-2 gap-3"><Field label="Preço de venda" value={product.price} onChange={value=>updateProduct(product.id,{price:value})}/><Field label="Custo direto unitário" value={product.productCost} onChange={value=>updateProduct(product.id,{productCost:value})}/><Field label="Taxas e impostos" value={product.fees} onChange={value=>updateProduct(product.id,{fees:value})} suffix="%"/><Field label="Vendas médias/mês" value={product.monthlyUnits} onChange={value=>updateProduct(product.id,{monthlyUnits:value})} suffix="un."/></div></div>)}</div><button onClick={addProduct} className="flex items-center gap-2 text-xs text-[#8d7852] dark:text-[#c7b182]"><Plus size={14}/> Adicionar outro produto</button><p className="text-xs text-black/35 dark:text-white/35 leading-relaxed">Custo direto inclui produção, matéria-prima, embalagem e outros valores que só existem quando o produto é vendido.</p></SetupGroup>
      <SetupGroup number="02" title="Estrutura mensal" help="São contas que chegam mesmo quando nenhuma venda acontece."><div className="space-y-3">{data.fixedCosts.map(cost => <div key={cost.id} className="flex flex-row gap-2 md:gap-4 items-center"><input aria-label="Nome do custo fixo" value={cost.label} onChange={event => updateCost(cost.id, { label: event.target.value })} className="bg-transparent border-b border-black/10 dark:border-white/10 py-2 md:py-3 text-xs md:text-sm outline-none focus:border-[#a68f63] flex-1 min-w-0" /><span className="relative w-[90px] md:w-[120px] shrink-0"><input aria-label={`Valor de ${cost.label}`} type="number" min="0" value={cost.value || ''} onChange={event => updateCost(cost.id, { value: Number(event.target.value) })} className="w-full rounded-lg bg-white/60 dark:bg-white/[0.05] border border-black/10 dark:border-white/10 py-2 md:py-3 pl-2 pr-6 md:pl-3 md:pr-7 text-xs md:text-base outline-none focus:border-[#a68f63] min-w-0" /><span className="absolute right-2 top-1/2 -translate-y-1/2 text-[9px] text-black/30 dark:text-white/30">R$</span></span><button aria-label={`Excluir ${cost.label}`} onClick={() => removeCost(cost.id)} className="text-black/25 dark:text-white/25 hover:text-red-500 flex justify-center shrink-0 w-6 md:w-8"><Trash2 size={15} /></button></div>)}</div><button onClick={addCost} className="flex items-center gap-2 text-xs text-[#8d7852] dark:text-[#c7b182] mt-3"><Plus size={14} /> Adicionar outro custo</button><div className="flex justify-between items-center border-t border-black/10 dark:border-white/10 pt-4 mt-4"><span className="text-xs text-black/45 dark:text-white/45">Total fixo mensal</span><strong className="font-serif text-lg md:text-xl shrink-0">{money.format(totalFixed)}</strong></div></SetupGroup>
      <SetupGroup number="03" title="Seu objetivo" help="A meta que você gostaria de retirar como lucro após pagar tudo."><div className="grid sm:grid-cols-2 gap-4"><Field label="Lucro desejado no mês" value={data.profitGoal} onChange={value => update('profitGoal', value)} /><Field label="Dias de venda no mês" value={data.workDays} onChange={value => update('workDays', value)} suffix="dias" /></div></SetupGroup>
      <div className="rounded-2xl bg-[#171716] dark:bg-white text-white dark:text-black p-7 flex flex-col justify-between min-h-48"><div><p className="text-[10px] uppercase tracking-[.2em] opacity-50 mb-3">Próximo passo</p><h3 className="text-2xl font-serif">Seus simuladores já estão conectados.</h3><p className="text-sm opacity-55 mt-3 leading-relaxed">Você pode voltar e alterar qualquer número. Os resultados serão recalculados na hora.</p></div><button onClick={onReady} className="self-start mt-6 rounded-full bg-white dark:bg-black text-black dark:text-white px-5 py-3 text-[10px] font-semibold uppercase tracking-[.16em]">Ver minha margem →</button></div>
    </div>
  </div>;
}

function SetupGroup({ number: step, title, help, children }: { number: string; title: string; help: string; children: ReactNode }) { return <section className="rounded-2xl border border-black/[0.08] dark:border-white/[0.09] bg-white/45 dark:bg-white/[0.035] p-6 md:p-7"><div className="flex gap-4 mb-6"><span className="text-[#a68f63] font-serif text-2xl">{step}</span><div><h3 className="font-serif text-2xl">{title}</h3><p className="text-xs text-black/40 dark:text-white/40 mt-1 leading-relaxed">{help}</p></div></div><div className="space-y-5">{children}</div></section>; }

function ProductPicker({ products, selected, onChange }: { products: Product[]; selected: string; onChange: (id: string) => void }) {
  return <div className="px-7 md:px-11 pt-7"><p className="meta-label">Analisar por produto</p><div className="flex flex-wrap gap-2">{products.map(product=><button key={product.id} onClick={()=>onChange(product.id)} className={`rounded-full px-4 py-2 text-xs border transition-all ${selected===product.id?'bg-[#171716] dark:bg-white text-white dark:text-black border-transparent':'border-black/10 dark:border-white/10 hover:border-[#a68f63]'}`}>{product.name || 'Produto sem nome'}</button>)}</div></div>;
}

function MarginTool({ data, product }: { data: BusinessData; product: Product }) {
  const fixed = data.fixedCosts.reduce((sum, cost) => sum + cost.value, 0), unitContribution = contribution(product), estimatedUnits = product.monthlyUnits || (unitContribution > 0 ? Math.ceil(fixed / unitContribution) : 0), fixedShare = estimatedUnits > 0 ? fixed / estimatedUnits : 0, netUnit = unitContribution - fixedShare, netMargin = product.price > 0 ? netUnit / product.price * 100 : 0;
  return <ToolShell eyebrow="Ferramenta 01" title={`Margem de ${product.name}`} description="Separamos a margem de contribuição da margem líquida estimada. Assim você enxerga o produto antes e depois do rateio da estrutura mensal." results={<><Metric label="Contribuição por unidade" value={money.format(unitContribution)} hero /><Metric label="Margem de contribuição" value={`${number.format(product.price > 0 ? unitContribution / product.price * 100 : 0)}%`} /><Metric label="Margem líquida estimada" value={`${number.format(netMargin)}%`} /><Advice>{product.price <= 0 ? 'Preencha preço e custos deste produto nos Dados do negócio.' : unitContribution <= 0 ? 'Este produto perde dinheiro antes mesmo de pagar a estrutura. Reveja preço, custo direto ou taxas.' : netUnit <= 0 ? 'O produto tem contribuição positiva, mas o volume informado ainda não paga a parcela estimada dos custos fixos.' : `No volume de ${number.format(estimatedUnits)} unidades, cada venda deixa aproximadamente ${money.format(netUnit)} após o rateio da estrutura.`}</Advice></>}><Summary label="Preço" value={money.format(product.price)} /><Summary label="Custo direto" value={money.format(product.productCost)} /><Summary label="Taxas" value={`${number.format(product.fees)}%`} /><Summary label="Rateio fixo/unidade" value={money.format(fixedShare)} /></ToolShell>;
}

function GoalTool({ data, product }: { data: BusinessData; product: Product }) {
  const fixed = data.fixedCosts.reduce((sum, cost) => sum + cost.value, 0), unitContribution = contribution(product);
  const units = unitContribution > 0 ? Math.ceil((fixed + data.profitGoal) / unitContribution) : 0, revenue = units * product.price, daily = data.workDays > 0 ? Math.ceil(units / data.workDays) : 0;
  return <ToolShell eyebrow="Ferramenta 02" title={`Meta usando ${product.name}`} description="Simula quantas unidades seriam necessárias se este produto fosse responsável por cobrir a estrutura e formar todo o lucro desejado." results={<><Metric label="Unidades necessárias no mês" value={`${number.format(units)} unidades`} hero /><Metric label="Faturamento necessário" value={money.format(revenue)} /><Metric label="Ritmo nos dias informados" value={`${number.format(daily)} por dia`} /><Advice>{unitContribution <= 0 ? 'Este produto ainda não possui contribuição positiva.' : data.profitGoal <= 0 ? 'Informe o lucro desejado em Dados do negócio.' : `Cada unidade contribui com ${money.format(unitContribution)}. Em uma operação com vários produtos, combine as contribuições do mix para construir uma meta mais realista.`}</Advice></>}><Summary label="Lucro desejado" value={money.format(data.profitGoal)} /><Summary label="Custos fixos" value={money.format(fixed)} /><Summary label="Contribuição unitária" value={money.format(unitContribution)} /><Summary label="Dias de venda" value={`${number.format(data.workDays)} dias`} /></ToolShell>;
}

function BreakEvenTool({ data, product }: { data: BusinessData; product: Product }) {
  const fixed = data.fixedCosts.reduce((sum, cost) => sum + cost.value, 0), unitContribution = contribution(product), rate = product.price > 0 ? unitContribution / product.price : 0;
  const revenue = rate > 0 ? fixed / rate : 0, units = unitContribution > 0 ? Math.ceil(fixed / unitContribution) : 0, safety = revenue * 1.1;
  return <ToolShell eyebrow="Ferramenta 03" title={`Equilíbrio de ${product.name}`} description="Mostra o mínimo necessário se este produto carregar sozinho os custos fixos. No mix real, cada produto participa conforme sua contribuição." results={<><Metric label="Faturamento de equilíbrio" value={money.format(safe(revenue))} hero /><Metric label="Quantidade mínima" value={`${number.format(units)} unidades`} /><Metric label="Meta com 10% de segurança" value={money.format(safe(safety))} /><Advice>{rate <= 0 ? 'Preencha a base ou corrija a margem negativa deste produto.' : `Ao alcançar ${number.format(units)} unidades, este produto cobre os ${money.format(fixed)} de estrutura. Use a margem de segurança para absorver variações.`}</Advice></>}><Summary label="Estrutura mensal" value={money.format(fixed)} /><Summary label="Contribuição unitária" value={money.format(unitContribution)} /><Summary label="Preço" value={money.format(product.price)} /><Summary label="Margem percentual" value={`${number.format(rate * 100)}%`} /></ToolShell>;
}

function ValuationTool({ data, update }: { data: BusinessData; update: <K extends keyof BusinessData>(key: K, value: BusinessData[K]) => void }) {
  const margin = data.annualRevenue > 0 ? data.annualProfit / data.annualRevenue : 0;
  const growthBonus = Math.max(-.5, Math.min(1.2, data.annualGrowth / 25));
  const dependencePenalty = Math.max(0, Math.min(.8, data.ownerDependence / 125));
  const multiple = Math.max(1.5, Math.min(4.5, 2.5 + growthBonus - dependencePenalty));
  const profitValue = safe(data.annualProfit * multiple);
  const revenueMultiple = Math.max(.15, Math.min(1.15, .25 + margin * 1.8 + Math.max(0, data.annualGrowth) / 200));
  const revenueValue = safe(data.annualRevenue * revenueMultiple);
  const center = profitValue && revenueValue ? (profitValue * .7 + revenueValue * .3) : profitValue || revenueValue;
  const low = center * .8, high = center * 1.2;
  return <ToolShell eyebrow="Ferramenta 04 — empresa" title="Valuation indicativo" description="Esta estimativa combina lucro anual e faturamento, ajustando crescimento e dependência do dono. É uma faixa gerencial, não um laudo de avaliação." results={<><Metric label="Faixa indicativa da empresa" value={center ? `${money.format(low)} — ${money.format(high)}` : money.format(0)} hero/><Metric label="Valor central estimado" value={money.format(center)}/><Metric label="Múltiplo de lucro aplicado" value={`${number.format(multiple)}×`}/><Advice>{data.annualRevenue<=0 || data.annualProfit<=0 ? 'Informe faturamento e lucro dos últimos 12 meses. Um valuation confiável também exige análise de dívidas, caixa, concentração de clientes, marca e contratos.' : data.ownerDependence>70 ? 'A dependência elevada do dono reduz a transferibilidade do negócio. Documentar processos e formar liderança pode aumentar valor.' : `A estimativa pondera 70% do método por lucro e 30% do método por receita. Margem atual: ${number.format(margin*100)}%.`}</Advice></>}><Field label="Faturamento dos últimos 12 meses" value={data.annualRevenue} onChange={value=>update('annualRevenue',value)}/><Field label="Lucro dos últimos 12 meses" value={data.annualProfit} onChange={value=>update('annualProfit',value)}/><Field label="Crescimento anual" value={data.annualGrowth} onChange={value=>update('annualGrowth',value)} suffix="%"/><Field label="Dependência do dono" value={data.ownerDependence} onChange={value=>update('ownerDependence',Math.min(100,value))} suffix="%"/><p className="xl:col-span-2 text-xs text-black/40 dark:text-white/40 leading-relaxed">Dependência do dono significa quanto a empresa precisa da presença pessoal dele para vender, operar e manter clientes. Quanto menor, mais transferível tende a ser o negócio.</p></ToolShell>;
}

function Summary({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-black/[0.08] dark:border-white/[0.08] p-4"><p className="text-[10px] uppercase tracking-[.15em] text-black/35 dark:text-white/35 mb-2">{label}</p><p className="font-serif text-xl">{value}</p></div>; }
